import type { Metadata } from "next";
import { Inter, Pinyon_Script, Berkshire_Swash } from "next/font/google";
import "./globals.css";
import ClientLayout from './clientLayout';

const inter = Inter({ subsets: ['latin'] });
const pinyon_script = Pinyon_Script({
   subsets: ['latin'],
   weight: ['400'],
});
const berkshire_swash = Berkshire_Swash({
   subsets: ['latin'],
   weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body className={`${inter.className} ${pinyon_script.className} ${berkshire_swash.className}`}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
