import type { Metadata } from "next";
import { Inter, Pinyon_Script, Berkshire_Swash, Metal, Felipa, Luxurious_Roman, Srisakdi } from "next/font/google";
import "./globals.css";
import ClientLayout from './clientLayout';
import Nav from "./components/nav";

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter'
});
const pinyon_script = Pinyon_Script({
   subsets: ['latin'],
   weight: ['400'],
   variable: '--font-pinyon-script'
});
const berkshire_swash = Berkshire_Swash({
   subsets: ['latin'],
   weight: ['400'],
   variable: '--font-berkshire-swash'
});
const metal = Metal({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-metal'
});
const felipa = Felipa({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-felipa'
});
const luxurious_roman = Luxurious_Roman({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-luxurious-roman'
});
const srisakdi = Srisakdi({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-srisakdi'
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body className={`${inter.variable} ${pinyon_script.variable} ${berkshire_swash.variable} ${metal.variable} ${felipa.variable} ${luxurious_roman.variable} ${srisakdi.variable}`}>
        <ClientLayout>
          <Nav />
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
